# Funding platforms for dursor
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Primary: GitHub Sponsors
github: [hampen2929]

# Alternative platforms (uncomment when set up)
# open_collective: dursor
# ko_fi: hampen2929
# buy_me_a_coffee: hampen2929

# Custom links (for future SaaS or other offerings)
# custom: ["https://dursor.dev/sponsor"]
